from . import errors as errors
from .logger import console_handler as console_handler, file_handler as file_handler, log_filename as log_filename, logger as logger
from _typeshed import Incomplete

class Client:
    api_key: Incomplete
    server_debug: Incomplete
    debug: Incomplete
    def __init__(self, api_key, debug: bool = ..., server_debug: bool = ...) -> None: ...
    def escape(self, value: str): ...
    async def close(self): ...
    async def solve_hcaptcha(self, site_key: str, page_url: str, rq_data: str, user_agent: str, invisible: int = ..., wait_for_solve: bool = ..., proxy: str = ...): ...
    async def wait_for_captcha_solve(self, request_id: str): ...
    async def solve_funcaptcha(self, publickey: str, surl: str = ..., pageurl: str = ..., wait_for_solve: bool = ...): ...
